# Absolute path for the package. Useful for referencing data directories. 
path: "/home/hsuh/Documents/p2t_ais"

# Choice of train / deploy / reinforce.
mode: "train"

# Environment to choose 
env: pendulum
env_name: "PendulumPixel-v0"

# Model settings.
model:
  z: 100 
  a : 4 
  reward: "RewardMLP"
  dynamics: "DynamicsMLP"
  compression: "CompressionMLP"

# Model names being loaded for training and evaluation.
load_model:
  compression: "compression_mlp_V2.pth"
  dynamics:    "dynamics_mlp_V2.pth"
  reward:      "reward_mlp_V2.pth"

# Model names being saved for training.
save_model:
  compression: "compression_mlp_V2.pth"
  dynamics:    "dynamics_mlp_V2.pth"
  reward:      "reward_mlp_V2.pth"

# Tensorboard directory name for the run.
tensorboard_dir: "online_rl2"
log_dir: "online_rl2.csv"

# Offline Training Parameters.
offline_train:
  num_epochs: 100 
  batch_size: 64 
  iniital_lr: 1e-3
  lr_scheduler: "StepLR"
  lr_step_size: 250
  lmbda: 0.01

# Online Training Parameters.
online_train:
  num_epochs: 30
  batch_size: 64 
  initial_lr: 1e-3

# Dataset parameters 
dataset:
  file: "data.csv"
  image_dir: "images"
  data_dir: "data/pendulum"
  policy: "random"
  num_episodes: 10
  episode_length: 200
